[tool.poetry]
name = "eindfeest"
version = "0.1.0"
description = ""
<<<<<<< HEAD
authors = ["vkpha <149399516+vkpha@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[tool.poetry.group.dev.dependencies]
nsp2visasim = "^1.3.1"

=======
authors = ["Kevin-Veenboer <135600479+Kevin-Veenboer@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


>>>>>>> a3e1ff1621af7fab201d30a0498888e45c912be0
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
